export const state = {
  AMap: null,
  map: null,
  geolocation: null,
  autoComplete: null,
  placeSearch: null,
  driving: null,
  walking: null,
  riding: null,
  transfer: null,
  currentPosition: null,
  currentAddress: "",
  currentAccuracy: null,
  currentCity: "",
  startMarker: null,
  accuracyCircle: null,
  stops: [],
  stopMarkers: new Map(),
  searchMarkers: [],
  searchPagination: {
    keyword: "",
    city: "",
    page: 1,
    pageSize: 10,
    total: 0,
    loaded: 0,
    loading: false,
    hasMore: false,
  },
  routeOverlays: [],
  originStopId: "",
  routeOrder: [],
  lastRouteStart: null,
  lastRouteStartLabel: "",
  lastRouteMode: "driving",
};
