export const state = {
  AMap: null,
  map: null,
  geolocation: null,
  autoComplete: null,
  placeSearch: null,
  driving: null,
  walking: null,
  riding: null,
  transfer: null,
  currentPosition: null,
  currentAddress: "",
  currentAccuracy: null,
  startMarker: null,
  accuracyCircle: null,
  stops: [],
  stopMarkers: new Map(),
  routeOverlays: [],
  originStopId: "",
  routeOrder: [],
  lastRouteStart: null,
  lastRouteStartLabel: "",
  lastRouteMode: "driving",
};
